services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: python3 server.py
    volumes:
      - ./server_embeddings/:/src/server_embeddings/
      - ./web_server/src/saved/:/src/web_server/src/saved/
      - ./web_server/src/static/:/src/web_server/src/static/
    env_file:
      - path: ./env/dev.env
        required: true # default
      - path: ./env/prod.env
        required: false
    depends_on:
      - qdrant
    restart: "always"
    tty: true
    networks:
      - internal

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ./qdrant_storage/:/qdrant/storage/
    restart: "always"
    tty: true
    networks:
      - internal
      
  nginx-nossl:
    profiles:
      - nossl
    image: nginx:stable-alpine
    volumes:
      - ./web_server/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web_server/src/static/:/app/static/:ro
      - ./nginx_cache/:/app/cache/:rw
    depends_on:
      - web_server
    ports:
      - 80:80
      - 20023:50051
    restart: "always"
    tty: true
    networks:
      internal:
        aliases:
          - nginx

  nginx-ssl:
    profiles:
      - ssl
    image: nginx:stable-alpine
    volumes:
      - ./web_server/config/nginx_ssl.conf:/etc/nginx/nginx.conf:ro
      - ./web_server/src/static/:/app/static/:ro
      - ./nginx_cache/:/app/cache/:rw
      - /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem:/etc/nginx/certs/privkey.pem
      - /etc/letsencrypt/live/www.${DOMAIN_NAME}/fullchain.pem:/etc/nginx/certs/wwwfullchain.pem
      - /etc/letsencrypt/live/www.${DOMAIN_NAME}/privkey.pem:/etc/nginx/certs/wwwprivkey.pem
    depends_on:
      - web_server
    ports:
      - 80:80
      - 443:443
      - 20023:50051
    restart: "always"
    tty: true
    networks:
      internal:
        aliases:
          - nginx

networks:
  internal:
    driver: bridge