services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: python3 server.py
    volumes:
      - ./server_embeddings/:/src/server_embeddings/
      - ./web_server/src/saved/:/src/web_server/src/saved/
      - ./web_server/src/static/:/src/web_server/src/static/
    env_file:
      - path: ./env/dev.env
        required: true # default
      - path: ./env/prod.env
        required: false
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ./qdrant_storage/:/qdrant/storage/
      
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./web_server/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web_server/src/static/:/app/static/:ro
    depends_on:
      - web_server
    ports:
      - 80:80
      - 20023:20023