# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x13transcript_encoding\"2\n\x0b\x44\x61taRequest\x12\x14\n\x0cinput_string\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x02\"\x1e\n\x0c\x44\x61taResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2m\n\x15StringAndArrayService\x12T\n\x0bProcessData\x12 .transcript_encoding.DataRequest\x1a!.transcript_encoding.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=38
  _globals['_DATAREQUEST']._serialized_end=88
  _globals['_DATARESPONSE']._serialized_start=90
  _globals['_DATARESPONSE']._serialized_end=120
  _globals['_STRINGANDARRAYSERVICE']._serialized_start=122
  _globals['_STRINGANDARRAYSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
